django_app/src/commodity/urls.py
from django.urls import path
from django.urls import path, re_path


app_name = 'commodity'

from . import main
urlpatterns = [
    # The home page
    path('index_old', main.inputForm, name='home'),
    path('index_old/<CMD>', main.inputForm, name='index_cmd'),
]

from . import views
urlpatterns += [
    path('index', views.index, name='index'),
    path('<int:page>', views.page, name='page'),
    path('<int:page>/calculate', views.calculate, name='calculate'),
    path('upload', views.upload, name='upload'),
    path('upload/calculate', views.upload_calculate, name='upload_calculate'),
]

# reverse('commodity:author-detail', kwargs={'pk': self.pk})

django_app/src/mysite/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', lambda request: HttpResponseRedirect('commodity/index')),
    path('commodity/', include('commodity.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_app/src/commodity/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class MyModel(models.Model):
    # file will be uploaded to MEDIA_ROOT/uploads
    upload = models.FileField(upload_to='uploads/')
    # or...
    # file will be saved to MEDIA_ROOT/uploads/2015/01/30
    upload = models.FileField(upload_to='uploads/%Y/%m/%d/')

class ObjectDetect(models.Model):
    img1 = models.ImageField('Image 1')
    img2 = models.ImageField('Image 2')
    name = models.CharField(default="ObjectDetect", max_length=200)
    createdate = models.DateTimeField('Date Created', auto_now_add=True)
    config = models.JSONField(default=None, null=True)
    out1 = models.ImageField(default=None, )
    out2 = models.ImageField(default=None, )
    outstring = models.CharField(default="", max_length=2000)


    def __str__(self):
        return self.name
        # return self.name + str(self.createdate)

    # def get_absolute_url(self):
    #     return reverse('upload:index')

from django.contrib.auth.models import User
from django.db import models

# class Author(models.Model):
#     name = models.CharField(max_length=200)
#     created_by = models.ForeignKey(User, on_delete=models.CASCADE)

class CommodityDetect(models.Model):
    Name = models.CharField(default="CommodityDetect", max_length=200)
    ConfigJson = models.JSONField(null=True)
    Img1 = models.ImageField()
    Img2 = models.ImageField()
    Img1Result = models.ImageField()
    Img2Result = models.ImageField()
    Date = models.DateTimeField('Date Created', auto_now_add=True)

    # created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    # def __str__(self):
    #     return f'{self.name} ({self.id})'

#---------------------------
class Author(models.Model):
    name = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('commodity:author-detail', kwargs={'pk': self.pk})

django_app/src/commodity/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
import time
import random

from django.conf import settings
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from commodity.utils.utils import PickleData

MAX_PAGE = 6

############### Config ###############
class ConfigForm(forms.Form):
    nms_thresh = forms.FloatField()
    score_thresh = forms.FloatField()
    # test = forms.FloatField()
CONFIG_KEYS = list(ConfigForm.base_fields.keys())
class ConfigClass:
    """" load or save config data"""
    def __init__(self):
        keys = CONFIG_KEYS
        default = 0
        config = dict()
        for k in keys:
            config[k] = default
        self.config = config

    def load(self, name="default"):
        # load from local file
        try:
            config_set = PickleData().load(name='config')
        except:
            config_set = dict()

        all_keys = list(self.config.keys())
        for k,v in config_set.items():
            if k in all_keys:
                self.config[k] = v
        pass
        return {"name": list(self.config.keys()),
                "value": list(self.config.values()),
                "dict": self.config,
                }
    def save(self, config, name="default"):
        Pickle = PickleData()
        Pickle.save(config, name='config')
        pass

############### Tools ###############
def path_local_to_media(path):
    """ convert local path to media path"""
    path = os.path.abspath(path)
    print(path)
    # is existed
    if os.path.exists(path):
        mpath = path
        pass
    else:
        raise ValueError(f'path not exists ! ')
    # is in MEDIA_ROOT
    p = Path(path)
    try:
        rpath = p.relative_to(settings.MEDIA_ROOT)
        print(rpath)
    except ValueError:
        print("path not in MEDIA_ROOT !")
        raise ValueError(f'path not in MEDIA_ROOT ! ')
        return None
    mpath = os.path.join(settings.MEDIA_URL, rpath)
    return mpath

def select_test_pairs(index, db_path=None):
    path1 = os.path.join(settings.MEDIA_ROOT, 'before.jpg')
    path2 = os.path.join(settings.MEDIA_ROOT, 'after.jpg')
    index = index % MAX_PAGE + 1

    path1 = os.path.join(settings.MEDIA_ROOT, f'db/{index}/{"1.jpg"}')
    path2 = os.path.join(settings.MEDIA_ROOT, f'db/{index}/{"2.jpg"}')

    return path1, path2

def default_page_context(nowpage, **kwargs):
    context = {}
    context['config_set'] = ConfigClass().load()
    timestamp = f"?t={round(time.time())}"
    context['ctrl'] = dict({"timestamp": timestamp,
                            "nowpage": nowpage,
                            "prevpage": max(nowpage - 1, 1),
                            "nextpage": nowpage % MAX_PAGE + 1,
                            "randpage": random.randint(1, MAX_PAGE)})
    path1, path2 = select_test_pairs(nowpage)
    context['detectors'] = dict({'img1urls': path_local_to_media(path1),
                                 'img2urls': path_local_to_media(path2),
                                 })
    return context

def page_get(request, **kwargs):
    nowpage = kwargs['page']
    context = default_page_context(nowpage)
    return render(request, 'my/index_page.html', context, )



############### UploadClass ###############
import os
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from pathlib import Path

class InputForm(forms.Form):
    img1 = forms.ImageField(label='Image 1')
    img2 = forms.ImageField(label='Image 2')
class UploadClass:
    def __init__(self):
        pass

    def save_file(self, file, name=None):
        """ Save Django InMemoryUploadedFile """
        data = file
        name = name if name is not None else file.name
        file_name = os.path.join(settings.MEDIA_ROOT, name)
        # file_name = MEDIA_ROOT
        print(file_name)
        if os.path.exists(file_name):
            os.remove(file_name)
        path = default_storage.save(file_name, ContentFile(data.read()))
        return Path(path)

    def save_img_to_local(self, img1, img2):
        path1 = self.save_file(img1, name='up1.jpg')
        path2 = self.save_file(img2, name='up2.jpg')
        return path1, path2

    def post(self, request, *args, **kwargs):
        form = InputForm(request.POST, request.FILES)
        data = form.cleaned_data if form.is_valid() else None
        print(data)
        context = default_page_context(1)

        context['interactive_message'] = 'success submit！'
        path1, path2 = self.save_img_to_local(data['img1'], data['img2'])
        context['detectors'] = dict({'img1urls': path_local_to_media(path1),
                                     'img2urls': path_local_to_media(path2),
                                     })
        context['ctrl']['isuploadpage'] = True
        return render(request, 'my/index_page.html', context, )

############### CalculateClass ###############
class CalculateClass:
    def __init__(self):
        pass
    def detect_commodity(self, path1, path2,config=None):
        from yolox import Object_Detection
        OD = Object_Detection(str(path1), str(path2),
                              config=config,
                              )
        pathout, results, table = OD.detect()

        info = results
        out1 = pathout[0]
        out2 = pathout[1]

        return info, out1, out2, table
    def post(self, request, *args, **kwargs):
        form = ConfigForm(request.POST)
        if form.is_valid():
            config = form.cleaned_data
            # save config data to local file
            ConfigClass().save(config)
        else:
            config = None
        page = kwargs['page']
        context = default_page_context(page)
        if "isuploadpage" in kwargs.keys():
            path1 = os.path.join(settings.MEDIA_ROOT, 'up1.jpg')
            path2 = os.path.join(settings.MEDIA_ROOT, 'up2.jpg')
            context['ctrl']['isuploadpage'] = True
        else:
            path1, path2 = select_test_pairs(page)

        info, out1, out2, table = self.detect_commodity(path1, path2, config=config)

        context['detectors'] = dict({'img1urls': path_local_to_media(path1),
                                     'img2urls': path_local_to_media(path2),
                                     })
        context['results'] = dict({'img1urls': path_local_to_media(out1),
                                   'img2urls': path_local_to_media(out2),
                                   'info': info,
                                   })
        context['table'] = table
        context['interactive_message'] = f'success calculation！config: {config}'
        return render(request, 'my/index_page.html', context, )

############### views ###############
def index(request, *args, **kwargs):
    return HttpResponseRedirect(reverse("commodity:page", kwargs={"page":1}))


def page(request, *args, **kwargs):
    return page_get(request, *args, **kwargs)

def calculate(request, *args, **kwargs):
    if request.method == "POST":
        handle = CalculateClass()
        response = handle.post(request, *args, **kwargs)
        return response
    elif request.method == "GET":
        response = page_get(request, page=kwargs['page'])
        return response

def upload(request, *args, **kwargs):
    if request.method == "POST":
        handle = UploadClass()
        response = handle.post(request, page=1)
        return response
    elif request.method == "GET":
        context = default_page_context(1)
        context['detectors'] = dict({'img1urls': settings.MEDIA_URL + 'up1.jpg',
                                     'img2urls': settings.MEDIA_URL + 'up2.jpg',
                                     })
        context['ctrl']['isuploadpage'] = True
        return render(request, 'my/index_page.html', context, )

def upload_calculate(request, *args, **kwargs):
    if request.method == "POST":
        response = calculate(request, page=1, isuploadpage=True)
        return response

django_app/src/commodity/templates/my/index.html
{% extends 'my/base-presentation.html' %}

{% block title %} Commodity Detection {% endblock title %}

 Specific CSS goes HERE
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}


<div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4 bg-gradient-faded-white">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3"
                rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Commodity Detection System
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>


<div class=" py-5"> </div>

<!--main-->
<div style="display: flex; justify-content: center; align-items:flex-start">
<!--  left-->
  <div style="position: relative; width:30%">
    <!--Select Images-->
    <div class=" py-5"> </div>
    <h2 class="text-center">Select images</h2>
    <section id="form-select">
      <div class="container py-3">
        <div class="row">
          <div class="col-lg-12 mx-auto d-flex justify-content-center flex-column">
            <h4 class="text-center">Upload images from local </h4>
            <form action="{% url 'commodity:home'%}" role="form" method="post" autocomplete="off", enctype="multipart/form-data">
                {% csrf_token %}
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6">
                    <label>Image 1</label>
                    <div class="input-group mb-4">
{#                        <input id="id-img1" type="file" required name="img1">#}
                      <input class="form-control" type="file" required name="img1" >
                    </div>
                  </div>
                  <div class="col-md-6 ">
                    <label>Image 2</label>
                    <div class="input-group">
{#                        <input id="id-img1" type="file" required name="img2">#}
                      <input class="form-control"  type="file" required name="img2" >
                    </div>
                  </div>

                </div>
                <div class="row">
                  <div class="col-md-12">
                    <button type="submit" class="btn bg-success w-100">Upload</button>
                  </div>
                </div>
              </div>
            </form>
            <h4 class="text-center py-2">Select images from database</h4>
            <div class="row">
              <div class="col-md-4">
                <form action="{% url 'commodity:index_cmd' "previous"%}" role="form" method="post" autocomplete="off">
                    {% csrf_token %}
{#                  <button href="{% url 'commodity:cmd' "next"%}" type="" class="btn bg-gradient-faded-info w-100">Previous</button>#}
                  <button type="submit" class="btn bg-gradient-faded-info w-100">Previous</button>
                </form>
              </div>
              <div class="col-md-4">
                <form action="{% url 'commodity:index_cmd' "random-new"%}" role="form" method="post" autocomplete="off">
                    {% csrf_token %}
                  <button type="submit" class="btn bg-success w-100">Random NEW</button>
                </form>
              </div>
              <div class="col-md-4">
                <form action="{% url 'commodity:index_cmd' "next"%}" role="form" method="post" autocomplete="off">
                    {% csrf_token %}
                  <button type="submit" class="btn bg-gradient-faded-info w-100">Next</button>
                </form>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
    <!--Detect and Calculate-->
    <div class=" py-5"> </div>
    <h2 class="text-center">Detect and calculate</h2>
    <section id="form-config">
    <div class="container py-3">
      <div class="row">
        <div class="col-lg-12 mx-auto d-flex justify-content-center flex-column">
          <h4 class="text-center">Set configuration </h4>
          <form action="{% url 'commodity:home'%}" role="form" method="post" autocomplete="off">
              {% csrf_token %}
            <div class="card-body">
              <div class="row">
                <div class="col-md-6">
                  <label>nms_thresh</label>
                  <div class="input-group mb-4">
                    <input class="form-control" placeholder="" name="nms_thresh" type="float" value="0.018" required >
                  </div>
                </div>
                <div class="col-md-6">
                  <label>iou_thresh</label>
                  <div class="input-group mb-4">
                    <input class="form-control" placeholder="" name="iou_thresh" type="float" value="0.2" required >
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <button type="submit" class="btn bg-success w-100">Calculate</button>
                </div>
              </div>
            </div>
          </form>


        </div>
      </div>
    </div>
  </section>

  </div>

<!--  right-->
  <div style="position: relative;  width:70%">

    <!--image input-->
    <div class=" py-3"> </div>
    <h2 class="text-center">Images to detected</h2>
    <div  style="display:flex; justify-content: center; align-items:flex-start">
      <div class="px-1" style="position:relative; width: 40%">
        <li><strong> Image 1 </strong></li>
        {% if detectors %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ detectors.img1urls }}>
        {% else %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src="/media/up1.jpg?t="+Math.random()>{% endif %}
      </div>
      <div class="px-1" style="position:relative; width: 40%">
        <li><strong> Image 2 </strong></li>
        {% if detectors %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ detectors.img2urls }}>
        {% else %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src="/media/up2.jpg?t="+Math.random()>{% endif %}
      </div>
    </div>
    <!--image output-->
    <div class=" py-3"> </div>
    <h2 class="text-center">Images after detection</h2>
  {% if table %}
    <div  style="display:flex; justify-content: center; align-items:flex-start">
      <div class="px-1" style="position:relative; width: 40%">
        <li><strong> Image 1 result </strong></li>
        {% if results %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ results.img1urls }}>
        {% else %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src="/media/up1--out.jpg?t="+Math.random()>{% endif %}
      </div>
      <div class="px-1" style="position:relative; width: 40%">
        <li><strong> Image 2 result </strong></li>
        {% if results %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ results.img2urls }}>
        {% else %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src="/media/up2--out.jpg?t="+Math.random()>{% endif %}
      </div>
    </div>
  {% else %}
      <div class=" py-2"> </div>
      <h6 class="text-center">Click "CALCULATE" button to start detection.</h6>
      <div class=" py-5"> </div>
  {% endif %}

    <!-- list of results-->
    <section class="pt-5 mt-5" id="table-ex1">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <div class="card">
              <div class="table-responsive">
                <h3 class="text-center">List of results</h3>
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      {% for col in table.colname %}
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                          {{ col }}</th>
                      {% endfor %}
                    </tr>
                  </thead>
                  <tbody>
                  {% for row in table.data %}
                    <tr>
                    {% for coli in row %}
                      <td class="align-middle text-center">
                        <span class="text-secondary text-xs font-weight-bold"> {{ coli }}</span>
                      </td>
                    {% endfor %}
                    </tr>
                  {% endfor %}



                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  <div class=" py-5"> </div>
  <div class=" py-5"> </div>


  </div>

</div>






{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}


{% endblock javascripts %}

django_app/src/commodity/templates/my/index_page.html
{% extends 'my/base-presentation.html' %}

{% block title %} Commodity Detection {% endblock title %}

 Specific CSS goes HERE
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}


<div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4 bg-gradient-faded-white">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3"
                rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Commodity Detection System
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>


<div class=" py-5"> </div>

<!--main-->
<div style="display: flex; justify-content: center; align-items:flex-start">
<!--  left-->
  <div style="position: relative; width:30%">
    <!--Select Images-->
    <div class=" py-5"> </div>
    <h2 class="text-center">Select images</h2>
    <section id="form-select">
      <div class="container py-3">
        <div class="row">
          <div class="col-lg-12 mx-auto d-flex justify-content-center flex-column">
            <h4 class="text-center">Upload images from local </h4>
            <form action="{% url 'commodity:upload'%}" role="form" method="post" autocomplete="off", enctype="multipart/form-data">
                {% csrf_token %}
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6">
                    <label>Image 1</label>
                    <div class="input-group mb-4">
{#                        <input id="id-img1" type="file" required name="img1">#}
                      <input class="form-control" type="file" required name="img1" >
                    </div>
                  </div>
                  <div class="col-md-6 ">
                    <label>Image 2</label>
                    <div class="input-group">
{#                        <input id="id-img1" type="file" required name="img2">#}
                      <input class="form-control"  type="file" required name="img2" >
                    </div>
                  </div>

                </div>
                <div class="row">
                  <div class="col-md-12">
                    <button type="submit" class="btn bg-success w-100">Upload</button>
                  </div>
                </div>
              </div>
            </form>
            <h4 class="text-center py-2">Select images from database</h4>
            <div class="row">
              <div class="col-md-4">
                <form action="{% url 'commodity:page' ctrl.prevpage %}" role="form" method="get" autocomplete="off">
{#                    {% csrf_token %}#}
{#                  <button href="{% url 'commodity:cmd' "next"%}" type="" class="btn bg-gradient-faded-info w-100">Previous</button>#}
                  <button type="submit" class="btn bg-gradient-faded-info w-100">Previous</button>
                </form>
              </div>
              <div class="col-md-4">
                <form action="{% url 'commodity:page' ctrl.randpage %}" role="form" method="get" autocomplete="off">
{#                    {% csrf_token %}#}
                  <button type="submit" class="btn bg-success w-100">Random NEW</button>
                </form>
              </div>
              <div class="col-md-4">
                <form action="{% url 'commodity:page' ctrl.nextpage %}" role="form" method="get" autocomplete="off">
{#                    {% csrf_token %}#}
                  <button type="submit" class="btn bg-gradient-faded-info w-100">Next</button>
                </form>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
    <!--Detect and Calculate-->
    <div class=" py-5"> </div>
    <h2 class="text-center">Detect and calculate</h2>
    <section id="form-config">
    <div class="container py-3">
      <div class="row">
        <div class="col-lg-12 mx-auto d-flex justify-content-center flex-column">
          <h4 class="text-center">Set configuration </h4>
        {% if ctrl.isuploadpage %}
          <form action="{% url 'commodity:upload_calculate'%}" role="form" method="post" autocomplete="off">
        {% else %}
          <form action="{% url 'commodity:calculate' ctrl.nowpage%}" role="form" method="post" autocomplete="off">
        {% endif %}
              {% csrf_token %}
            <div class="card-body">
              <div class="row">
              {% for name, value in config_set.dict.items %}
                <div class="col-md-6">
                  <label>{{ name }}</label>
                  <div class="input-group mb-4">
                    <input class="form-control" placeholder="" name="{{ name }}" type="float" value="{{ value }}" required >
                  </div>
                </div>
              {% endfor %}
              </div>
              <div class="row">
                <div class="col-md-12">
                  <button type="submit" class="btn bg-success w-100">Calculate</button>
                </div>
              </div>
            </div>
          </form>


        </div>
      </div>
    </div>
  </section>

  </div>

<!--  right-->
  <div style="position: relative;  width:70%">

    <!--image input-->
    <div class=" py-3"> </div>
    <h2 class="text-center">Images to detected</h2>
    <div  style="display:flex; justify-content: center; align-items:flex-start">
      <div class="px-1" style="position:relative; width: 40%">
        <li><strong> Image 1 </strong></li>
        {% if detectors %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ detectors.img1urls | add:ctrl.timestamp }}>
        {% else %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ "/media/up1.jpg" | add:ctrl.timestamp }}>
        {% endif %}
      </div>
      <div class="px-1" style="position:relative; width: 40%">
        <li><strong> Image 2 </strong></li>
        {% if detectors %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ detectors.img2urls | add:ctrl.timestamp }}>
        {% else %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ "/media/up2.jpg" | add:ctrl.timestamp }}>
        {% endif %}
      </div>
    </div>
    <!--image output-->
    <div class=" py-3"> </div>
    <h2 class="text-center">Images after detection</h2>
  {% if table %}
    <div  style="display:flex; justify-content: center; align-items:flex-start">
      <div class="px-1" style="position:relative; width: 40%">
        <li><strong> Image 1 result </strong></li>
        {% if results %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ results.img1urls | add:ctrl.timestamp }}>
        {% else %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ "/media/up1--out.jpg" | add:ctrl.timestamp }}>
        {% endif %}
      </div>
      <div class="px-1" style="position:relative; width: 40%">
        <li><strong> Image 2 result </strong></li>
        {% if results %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ results.img2urls | add:ctrl.timestamp }}>
        {% else %}<img style="position:relative; height:100%; width: 100%; border-radius: 10px;" alt="Image placeholder" src={{ "/media/up2--out.jpg" | add:ctrl.timestamp }}>
        {% endif %}
      </div>
    </div>
  {% else %}
      <div class=" py-2"> </div>
      <h6 class="text-center">Click "CALCULATE" button to start detection.</h6>
      <div class=" py-5"> </div>
  {% endif %}

    <!-- list of results-->
    <section class="pt-5 mt-5" id="table-ex1">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <div class="card">
              <div class="table-responsive">
                <h3 class="text-center">List of results</h3>
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      {% for col in table.colname %}
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                          {{ col }}</th>
                      {% endfor %}
                    </tr>
                  </thead>
                  <tbody>
                  {% for row in table.data %}
                    <tr>
                    {% for coli in row %}
                      <td class="align-middle text-center">
                        <span class="text-secondary text-xs font-weight-bold"> {{ coli }}</span>
                      </td>
                    {% endfor %}
                    </tr>
                  {% endfor %}



                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  <div class=" py-5"> </div>
  <div class=" py-5"> </div>


  </div>

</div>






{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}


{% endblock javascripts %}